# Authbox display configuration
---
apiVersion: 1.0
kind: Display
metadata:
  format: "1602"  # 16 chars, 2 lines
spec:
  init:
    state: INIT
  states:
    INIT:  # INIT state doesn't require args
      lines:
        # "0123456789ABCDEF"  <-- Ruler
        - "Authbox"
        - "Starting up..."
    WAITING:
      seq:
        - duration: 2000
          lines:
            # "0123456789ABCDEF"  <-- Ruler
            - "Badge to start"
            - "ID: {machine}"
        - duration: 2000
          refresh: 1000
          lines:
            # "0123456789ABCDEF"  <-- Ruler
            - "Badge to start"
            - "idle: {time}"
        - duration: 2000
          refresh: 1000
          lines:
            # "0123456789ABCDEF"  <-- Ruler
            - "Badge to start"
            - "firmware: {version}"
    SCANNED:
      lines:
        # "0123456789ABCDEF"  <-- Ruler
        - "# {id}"
        - "Verifying..."
    FOUND_NOT_AUTHORIZED:
      lines:
        # "0123456789ABCDEF"  <-- Ruler
        - "{id}"
        - "Not Authorized"
    NOT_FOUND:
      lines:
        # "0123456789ABCDEF"  <-- Ruler
        - "Not Recognized"
        - "Wrong badge?"
    AUTHORIZED:
      seq:
        - duration: 2000  # show for 2 sec
          lines:
            - "Authorized"
            - "Green to start"
        - duration: 2000  # show for 2 sec
          lines:
            - "Authorized"
            - "Waiting..."
    RUNNING:          
      seq:
        - duration: 4000 # show for 4sec
          refresh: 250 # refresh timer 4x /sec
          lines:
          # "0123456789ABCDEF"  <-- Ruler
          - "Time Remaining"
          - "{time}"
        - duration: 4000 # show for 4sec
          lines:
          # "0123456789ABCDEF"  <-- Ruler
          - "Active User"
          - "{id}"
      refresh: 0


